// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logic

import (
	"github.com/google/wire"
	"tidys-go/infra"
	"tidys-go/logic/auth"
	"tidys-go/logic/notes"
	repository3 "tidys-go/logic/notes/repository"
	"tidys-go/logic/spaces"
	repository2 "tidys-go/logic/spaces/repository"
	"tidys-go/logic/tags"
	"tidys-go/logic/tags/repository"
	"tidys-go/logic/user"
)

// Injectors from wire.go:

func initialize() *AppService {
	db := infra.ProvideDB()
	userRepo := user.NewUserRepo(db)
	service := user.NewService(userRepo)
	authService := auth.NewService(service)
	tagRepo := repository.NewTagRepo(db)
	tagGroupRepo := repository.NewTagGroupRepo(db)
	tagsService := tags.NewService(tagRepo, tagGroupRepo)
	spaceRepo := repository2.NewSpaceRepo(db)
	memberRepo := repository2.NewMemberRepo(db)
	inviteRepo := repository2.NewInviteRepo(db)
	spacesService := spaces.NewService(spaceRepo, memberRepo, inviteRepo, service)
	noteRepo := repository3.NewNoteRepo(db)
	notesService := notes.NewService(noteRepo)
	appService := &AppService{
		Auth:  authService,
		User:  service,
		Tag:   tagsService,
		Space: spacesService,
		Note:  notesService,
	}
	return appService
}

// wire.go:

type AppService struct {
	Auth  *auth.Service
	User  *user.Service
	Tag   *tags.Service
	Space *spaces.Service
	Note  *notes.Service
}

var svcSet = wire.NewSet(user.NewService, auth.NewService, tags.NewService, spaces.NewService, notes.NewService)

var providerSet = wire.NewSet(infra.ProvideDB, infra.ProvideRDB)

var repoSet = wire.NewSet(user.NewUserRepo, repository.NewTagRepo, repository.NewTagGroupRepo, repository2.NewSpaceRepo, repository2.NewMemberRepo, repository2.NewInviteRepo, repository3.NewNoteRepo)
